# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
#url: https://blog.csdn.net/u011760056
date_format: "ordinal"
title: 浣花洗剑
subtitle: "事了拂衣去，深藏功与名"
description: "paul大叔的个人博客"
keywords: IT老兵, Huanren Wang, paul
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Huanren Wang
organization: 
organization_url: 
github_username: paul-wanghr
location: Nanjing, China
email: whrgxl8687@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: paul-wanghr/paul-wanghr.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: paul-wanghr
    repo: paul-wanghr/paul-wanghr.github.io
    oauth:
        client_id: 9d3aea1fe61f037d06a6
        client_secret: a55022988b1240cf2092faa4f9358bf548ec087f
    #    https://github.com/gitalk/gitalk#install
gitalk:
    enable: true
    owner: paul-wanghr
    repo:  paul-wanghr/paul-wanghr.github.io
    clientID: 7732f1086fa71655fd7c
    clientSecret: c4f195b5a2a1fe3f411982e3f7dee5d40b2ab305
    admin: paul-wanghr
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
